export const adverbsData =[
    [
        "Not",
        "Also",
        "Very",
        "Often",
        "However",
        "Too",
        "Usually",
        "Really",
        "Early",
        "Never"
    ],
    [
        "Always",
        "Sometimes",
        "Together",
        "Likely",
        "Simply",
        "Generally",
        "Instead",
        "Actually",
        "Again",
        "Rather"
    ],
    [
        "Almost",
        "Especially",
        "Ever",
        "Quickly",
        "Probably",
        "Already",
        "Below",
        "Directly",
        "Therefore",
        "Else"
    ],
    [
        "Thus",
        "Easily",
        "Eventually",
        "Exactly",
        "Certainly",
        "Normally",
        "Currently",
        "Extremely",
        "Finally",
        "Constantly"
    ],
    [
        "Properly",
        "Soon",
        "Specifically",
        "Ahead",
        "Daily",
        "Highly",
        "Immediately",
        "Relatively",
        "Slowly",
        "Fairly"
    ]
]
export const adverbsData2 =[
    [
        "Primarily",
        "Completely",
        "Ultimately",
        "Widely",
        "Recently",
        "Seriously",
        "Frequently",
        "Fully",
        "Mostly",
        "Naturally"
    ],
    [
        "Nearly",
        "Occasionally",
        "Carefully",
        "Clearly",
        "Essentially",
        "Possibly",
        "Slightly",
        "Somewhat",
        "Equally",
        "Greatly"
    ],
    [
        "Necessarily",
        "Personally",
        "Rarely",
        "Regularly",
        "Similarly",
        "Basically",
        "Closely",
        "Effectively",
        "Initially",
        "Literally"
    ],
    [
        "Mainly",
        "Merely",
        "Gently",
        "Hopefully",
        "Originally",
        "Roughly",
        "Significantly",
        "Totally",
        "Twice",
        "Elsewhere"
    ],
    [
        "Everywhere",
        "Obviously",
        "Perfectly",
        "Physically",
        "Successfully",
        "Suddenly",
        "Truly",
        "Virtually",
        "Altogether",
        "Anyway"
    ]
]
export const adverbsData3 =[
    [
        "Automatically",
        "Deeply",
        "Definitely",
        "Deliberately",
        "Hardly",
        "Readily",
        "Terribly",
        "Unfortunately",
        "Forth",
        "Briefly"
    ],
    [
        "Moreover",
        "Strongly",
        "Honestly",
        "Previously",
        "As",
        "There",
        "When",
        "How",
        "So",
        "Up"
    ],
    [
        "Out",
        "No",
        "Only",
        "Well",
        "Then",
        "First",
        "Where",
        "Why",
        "Now",
        "Around"
    ],
    [
        "Once",
        "Down",
        "Off",
        "Here",
        "Tonight",
        "Away",
        "Today",
        "Far",
        "Quite",
        "Later"
    ],
    [
        "Above",
        "Yet",
        "Maybe",
        "Otherwise",
        "Near",
        "Forward",
        "Somewhere",
        "Anywhere",
        "Please",
        "Forever"
    ]
]
export const adverbsData4 =[
    [
        "Somehow",
        "Absolutely",
        "Abroad",
        "Yeah",
        "Nowhere",
        "Tomorrow",
        "Yesterday",
        "The",
        "To",
        "In"
    ],
    [
        "On",
        "By",
        "More",
        "About",
        "Such",
        "Through",
        "New",
        "Just",
        "Any",
        "Each"
    ],
    [
        "Much",
        "Before",
        "Between",
        "Free",
        "Right",
        "Best",
        "Since",
        "Both",
        "Sure",
        "Without"
    ],
    [
        "Back",
        "Better",
        "Enough",
        "Lot",
        "Small",
        "Though",
        "Less",
        "Little",
        "Under",
        "Next"
    ],
    [
        "Hard",
        "Real",
        "Left",
        "Least",
        "Short",
        "Last",
        "Within",
        "Along",
        "Lower",
        "True"
    ]
]
export const adverbsData5 =[
    [
        "Bad",
        "Across",
        "Clear",
        "Easy",
        "Full",
        "Close",
        "Late",
        "Proper",
        "Fast",
        "Wide"
    ],
    [
        "Item",
        "Wrong",
        "Ago",
        "Behind",
        "Quick",
        "Straight",
        "Direct",
        "Extra",
        "Morning",
        "Pretty"
    ],
    [
        "Overall",
        "Alone",
        "Bright",
        "Flat",
        "Whatever",
        "Slow",
        "Clean",
        "Fresh",
        "Whenever",
        "Cheap"
    ],
    [
        "Thin",
        "Cool",
        "Fair",
        "Fine",
        "Smooth",
        "False",
        "Thick",
        "Collect",
        "Nearby",
        "Wild"
    ],
    [
        "Apart",
        "None",
        "Strange",
        "Tourist",
        "Aside",
        "Loud",
        "Super",
        "Tight",
        "Gross",
        "Ill", 
        "Downtown",
        "Honest",
        "Ok",
        "Pray",
        "Weekly",
        ""
    ]
]
