export const prepositionsData =[
    [
        "Of",
        "With",
        "At",
        "From",
        "Into",
        "During",
        "Including",
        "Until",
        "Against",
        "Among"
    ],
    [
        "Throughout",
        "Despite",
        "Towards",
        "Upon",
        "Concerning",
        "To",
        "In",
        "For",
        "On",
        "By"
    ],
    [
        "About",
        "Like",
        "Through",
        "Over",
        "Before",
        "Between",
        "After",
        "Since",
        "Without",
        "Under"
    ],
    [
        "Within",
        "Along",
        "Following",
        "Across",
        "Behind",
        "Beyond",
        "Plus",
        "Except",
        "But",
        "Up"
    ],
    [
        "Out",
        "Around",
        "Down",
        "Off",
        "Above",
        "Near",
    ]
]