export const pronounsData =[
    [
        "Your",
        "I",
        "They",
        "Their",
        "We",
        "Who",
        "Them",
        "Its",
        "Our",
        "My"
    ],
    [
        "Those",
        "He",
        "Us",
        "Her",
        "Something",
        "Me",
        "Yourself",
        "Someone",
        "Everything",
        "Itself"
    ],
    [
        "Everyone",
        "Themselves",
        "Anyone",
        "Him",
        "Whose",
        "Myself",
        "Everybody",
        "Ourselves",
        "Himself",
        "Somebody"
    ],
    [
        "Yours",
        "Herself",
        "Whoever",
        "You",
        "That",
        "It",
        "This",
        "What",
        "Which",
        "These"
    ],
    [
        "His",
        "She",
        "Lot",
        "Anything",
        "Whatever",
        "Nobody",
        "None",
        "Mine",
        "Anybody",
        "Some"
    ],
    [
        "There",
        "All",
        "Where",
        "Another",
        "Same",
        "Certain",
        "Nothing",
        "Self",
        "Nowhere",
        ""
    ],
    [
        "There",
        "All",
        "Where",
        "Another",
        "Same",
        "Certain",
        "Nothing",
        "Self",
        "Nowhere",
        ""
    ]
]