export const businessWorkOfficeBank =[
    [
        "Begin the work ",
        "I’m looking forward to set up my own business ",
        "How’s your work going? ",
        "I’m gonna get to work ",
        "Business is business ",
        "We have a deal ",
        "Let’s work ",
        "To be on time ",
        "I have an interview work ",
        "You’re doing a great job "
    ],
    [
        "Pay me what you owe me ",
        "Your payment is overdue ",
        "Let me work ",
        "You are behind with the payment ",
        "I need a salary raise ",
        "I’m at work ",
        "I am looking for a job ",
        "It’s been a pleasure to do business with you",
        "Work as a team ",
        "Are you ready to work? "
    ],
    [
        "We have a meeting ",
        "They turn down my offer ",
        "How much do I owe you? ",
        "Can I pay you by credit card? ",
        "I don’t have money ",
        "I need money to pay my debts ",
        "Without money, nothing is done ",
        "You need a guarantor ",
        "You are very good customer ",
        "He’s making a lot of money "
    ],
    [
        "I’d like to apply for a loan ",
        "I want to withdraw (deposit) some money ",
        "I want to make a transfer ",
        "I can’t stand to be online ",
        "He’s charging his money ",
        "We have to open up a checking account. ",
        "I need to use my saving ",
        "You have a debts in your account ",
        "Write it ",
        "Print it "
    ],
    [
        "Copy ",
        "Paste ",
        "Answer the phone ",
        "Please, call me some clients ",
        "I want my money back ",
        "Can I ask you a question? ",
        "What are the interest rates? ",
        "Who’s calling? ",
        "The line is busy ",
        "You dial the wrong number "
    ],
    [
        "Could I leave a message? ",
        "Leave your message after the tone",
        "Send me an e-mail ",
        "To be off work ",
        "I’m tired of working the same ",
        "Help me with this work ",
        "I’m working very hard ",
        "That’s an easy work ",
        "How much money do you make? ",
        "He is millionaire "
    ],
    [
        "I wanna talk to the manager right now ",
        "Money doesn’t busy the happiness ",
        "I made a mistake ",
        "You have an error in your credit ",
        "Good job ",
        "To fall in business ",
        "I quit ",
        "You are fired ",
        "I need my liquidation",
        "Go on, go ahead "
    ],
    [
        "The boss is stingy ",
        "I’m broke ",
        "We’ll close ours doors ",
        "Go out of business ",
        "Our budget is high ",
        "The payroll is getting checked ",
        "I need the documents ",
        "Sign with the boss ",
        "I erased all the information by mistake ",
        "The computer is damaged "
    ],
    [
        "We must make a back up ",
        "The company is going down ",
        "The company is improving ",
        "The company us growing fast ",
        "Did you already pay the taxes? ",
        "Yes, I did ",
        "No I didn’t  ",
        "Not yet ",
        "Get ne all the bills ",
        "We have to pay every debt "
    ],
    [
        "I’ll sue the company ",
        "The company laid off 20 workers ",
        "That sake was a bad deal ",
        "The business went bankrupt ",
        "At last I got it ",
        "Finish the work",
        "",
        ""
    ]
]