export const church =[
    [
        "I’m going to the church now ",
        "I want to listen the mass ",
        "I want to say a prayer ",
        "The priest left a good message ",
        "The nun is helping people ",
        "I like psalm 91 ",
        "I always read the bible ",
        "I pray to god ",
        "The convent is near here ",
        "The nun is in the monastery "
    ],
    [
        "There is a mass at the cathedral ",
        "Miracles are possible ",
        "The priest is at the chapel ",
        "The bishop is very old ",
        "I would like to see the pope ",
        "I want to preach the gospel ",
        "You are sinner ",
        "Let’s listen the sermon ",
        "Jesus loves you ",
        "Jesus Christ died on the cross for you and me "
    ],
    [
        "All your sins will be forgiven ",
        "I love Christian music ",
        "What is your favorite Christian music? ",
        "I love “God’s pact” ",
        "God is merciful ",
        "Our father ",
        "Who art in heaven ",
        "Hallowed by the name ",
        "On earth as it is in heaven ",
        "Give us this day our daily bread "
    ],
    [
        "And forgive us our trespasses ",
        "As we forgive those who trespass against us ",
        "And lead us not intro temptation ",
        "But deliver us from evil ",
        "Amen",
        "Alleluia ",
        "God bless you ",
        "God opens and close doors ",
        "Holy week is to reflect ",
        "I can do everything through Christ who strengthens me "
    ],
    [
        "What is the chapter in the bible? ",
        "In which verse do I find it? ",
        "Charter 15, verse 1 ",
        "God is our light and the only hope ",
        "Which biblical quotes is it? ",
        "Did you bring the bible? ",
        "I work for god’s kingdom ",
        "Praise and glory to our lord Jesus Christ ",
        "God is father, son and holy spirit ",
        "Peace be with you "
    ],
    [
        "Ordered and will give you, seek and find ",
        "The lord is my shepherd shall not want  ",
        "Did you confess to the priest? ",
        "He married by the church ",
        "Are you Christian? ",
        "What’s your religion? ",
        "God willing ",
        "God almighty ",
        "Thanks god that .. ",
        "God only knows "
    ],
    [
        "For God’s sake! ",
        "You have to edify your mind ",
        "I open my heart to god ",
        "God takes the control of my life ",
        "You decide between the good and evil ",
        "The commands are to be followed ",
        "Love your neighbor as yourself ",
        "The salvation depends on yourself ",
        "Seek Christ to save your soul ",
        "Regret of your sins and deliver your heart ",
        "If we are faithful, we will get the eternal life ",
    ],

]