export  const homeFrase=[
    [
        "Welcome to my house ",
        "Come in ",
        "Open it ",
        "Get up",
        "Hello, Anybody home? ",
        "Open the door ",
        "Have a seat ",
        "Come here",
        "The phone is ringing ",
        "Who’s calling? "
    ],
    [
        "Watch T.V ",
        "Do the homework ",
        "Do the dishes ",
        "Mop the floor ",
        "Clean your room ",
        "Sweep the floor ",
        "Paint the house ",
        "Change the curtain ",
        "Do the laundry",
        "Iron the clothes "
    ],
    [
        "Pick up the phone ",
        "Close the windows ",
        "Turn on the light ",
        "Turn off the T.V",
        "Turn on the water bomb ",
        "Do the chores?   ",
        "Clean the house ",
        "Mowing the lawn ",
        "Set the table ",
        "Walk the dog "
    ],
    [
        "Water the plants",
        "Brush the wall ",
        "The pipe is leaking ",
        "The dog is barking ",
        "Hang a picture ",
        "What’s cooking? ",
        "Cook a special meal ",
        "I am hungry ",
        "I am thirsty ",
        "It smells delicious "
    ],
    [
        "It tastes good ",
        "Feed the cat ",
        "I have my lunch ",
        "Which one is my dish? ",
        "Would you like to eat something ? ",
        "I need a drink ",
        "The dinner is ready ",
        "Eat your food ",
        "Drink water ",
        "Take a bath"
    ],
    [
        "Take a shower ",
        "Brush my teeth",
        "Get dress ",
        "Put on my clothes ",
        "Take off my clothes ",
        "Stay at home ",
        "Use the investor ",
        "Fix the T:V ",
        "Make a family party ",
        "Take care of children "
    ],
    [
        "Take out the garbage ",
        "Go to bed ",
        "I am leaving ",
        "I wanna go home ",
        "Get home ",
        "Call me ",
        "Call me back later ",
        "Get out of my house",
        "Rest at home ",
        "Rebuilt the house "
    ],
    [
        "Lock the door ",
        "Sell the house ",
        "Listen to the news ",
        "Carry water ",
        "Do chores ",
        "White letters ",
        "Talking on the phone ",
        "I’m cooking something",
        "Take a nap ",
        "It’s raining, so I stay home "
    ],
    [
        "Studying for a test tomorrow ",
        "Thinking about the future ",
        "He eats a lot of fruit ",
        "I enjoy with my family ",
        "Have a good breakfast ",
        "Surf on the net ",
        "Play a sport ",
        "I’m helping my mom at home ",
        "I download music ",
        "Can you come over tonight? "
    ],
    [
        "Make yourself at home ",
        "Leave the house ",
        "I return home ",
    ]
]
