export const schoolUniversityEducation =[
    [
        "School is our second house ",
        "Good morning class ",
        "My teacher name is John ",
        "Pass the list ",
        "Present ",
        "Here ",
        "Sign ",
        "Sit down ",
        "Stand up ",
        "Read the book "
    ],
    [
        "Write the notebook ",
        "Lend me your pencil ",
        "Raise your hands ",
        "Listen to me ",
        "Look at me ",
        "Pay attention ",
        "Shut up ",
        "Silence ",
        "Repeat after me ",
        "Can I go to the bathroom? "
    ],
    [
        "Answer the question ",
        "Any question? ",
        "Do you understand? ",
        "Let’s pronounce ",
        "Copy in the notebook ",
        "Study at home",
        "Explain the class ",
        "Write it down ",
        "Next page ",
        "May I borrow your pencil "
    ],
    [
        "Don’t speak in class ",
        "Yes, I understand ",
        "Who wants to read? ",
        "Search information",
        "Find out the right answer ",
        "What’s the meaning of ...?",
        "Are you having mathematical problem? ",
        "It doesn’t make sense ",
        "Improve your grades",
        "You fail in the exam "
    ],
    [
        "The exam was postponed ",
        "Shut off the cellphone ",
        "Take off the cap ",
        "Think it over ",
        "Let’s have a break ",
        "Don’t eat in class ",
        "Don’t chew gum ",
        "Parent’s meeting",
        "I’ll take you to the principal ",
        "He was suspended for his behavior "
    ],
    [
        "What’s your major?",
        "I’m majoring medicine ",
        "What do you want to in the future? ",
        "I want to be an accountant ",
        "My favorite subject is biology ",
        "How many subjects do you take? ",
        "I’m taking six subjects ",
        "Which university would you go? ",
        " My graduation is tomorrow ",
        "I graduated from high school "
    ],
    [
        "Where is the bookstore? ",
        "How much does the book cost?",
        "I have to go to the library ",
        "The place is closed ",
        "We were at school together ",
        "We make a very good team ",
        "I missed two classes yesterday ",
        "Don’t interrupt me ",
        "If you read, you lean ",
        "If you learn, never forgot "
    ],
    [
        "It is a very easy exam ",
        "This exam is hard ",
        "It’s important to take technical course ",
        "What are your skills? ",
        "I’m good at speaking in public ",
        "Who knows nothing, nothing worth ",
        "Educate is taught to live better",
        "Student is studying a day earlier ",
        "Teaching is learning twice ",
        "Student life is sacrifice and reward success "
    ],
    [
        "Educate children will not have to educate adults ",
        "Science is true wisdom ",
        "I want to get a bachelor’s degree ",
        "Doctor’s degree is the highest level ",
        "My goal is to make a master’s degree ",
        "Get out of the classroom ",
        "The math teacher isn’t very nice ",
        "Take care everybody ",
        "Have a nice weekend ",
        "Let them go "
    ],
    [
        "We see in forty-five minutes ",
        "How far do you travel to school? ",
        "Class dismissed ",
        "See you next class ",
    ]
]